d={"monday","tuesday","wednesday","thursday","friday","saturday"}
print(d)
print(type(d))
d={"monday","tuesday","wednesday","thursday","friday","saturday"}
d.add("sunday")
print(d)
months={"jan","feb","mar","apr"}
print(months)
months.update(["may","jun","jul"])
print(months)
months={"jan","feb","mar","apr"}
print(months)
months.discard("apr")
print(months)
months={"jan","feb","mar","apr"}
print(months)
months.remove("feb")
print(months)
days={"monday","tuesday","wednesday","thursday","friday"}
print(days)
days.pop()
print(days)
a={"monday","tuesday","wednesday","saturday"}
b={"thursday","friday","saturday","sunday","monday"}
print(a.union(b))
days1={"mon","tue","wed","sat"}
days2={"thr","fri","sat","sun","mon"}
print(days1.intersection(days2))
days1={"mon","tue","wed","sat"}
days2={"thr","fri","sat","sun","mon"}
print(days1.difference(days2))
set1={1,2,3,4}
set2={1,2,3,4,5,6,7,8,9}
print(set1.issubset(set2))
print(set2.issubset(set1))
mrec={"civil","eee","mech","ece","cse","it","csm","csd","csc","iot","baiml"}
print(mrec)
print(sorted(mrec))
mrec={"civil","eee","mech","ece","cse","it","csm","csd","csc","iot","baiml"}
print(mrec)
print(len(mrec))
mrec={"civil","eee","mech","ece","cse","it","csm","csd","csc","iot","baiml"}
print(mrec)
print(max(mrec))
mrec={"civil","eee","mech","ece","cse","it","csm","csd","csc","iot","baiml"}
print(min(mrec))
fee={135000,135000,135000,800000,1400000,8000000,1250000,110000,1600000,750000,750000}
print(sum(fee))
x={"apple","banana","cherry"}
y={"google","microsoft","apple"}
x.symmetric_difference_update(y)
y.symmetric_difference(x)
print(x)
print(y)
days={"mon","tue","wed","thur","fri"}
days.clear()
print(days)

